### ISSUE TITLE
NullPointerException ListAdapter.getCount();

### ISSUE THREAD

**Issue by cesards** [etsy/AndroidStaggeredGrid#45]
I'm getting an error just doing setContentView.

Here is my list layout:

```
<com.etsy.android.grid.StaggeredGridView
      android:id="@+id/product_grid"
      xmlns:android="http://schemas.android.com/apk/res/android"
      xmlns:app="http://schemas.android.com/apk/res-auto"
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      app:column_count_landscape="3"
      app:column_count_portrait="2"
      app:grid_paddingBottom="@dimen/padding_medium"
      app:grid_paddingLeft="@dimen/padding_medium"
      app:grid_paddingRight="@dimen/padding_medium"
      app:grid_paddingTop="@dimen/padding_medium"
      app:item_margin="@dimen/padding_medium"/>
```

Here the staktrace:

```
java.lang.NullPointerException: Attempt to invoke interface method 'int android.widget.ListAdapter.getCount()' on a null object reference
            at com.etsy.android.grid.ExtendableListView.getLastVisiblePosition(ExtendableListView.java:1828)
            at android.widget.AdapterView.onInitializeAccessibilityEvent(AdapterView.java:957)
            at android.widget.AbsListView.onInitializeAccessibilityEvent(AbsListView.java:1443)
            at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:4946)
            at android.view.View.sendAccessibilityEventUnchecked(View.java:4933)
            at android.view.View$SendViewStateChangedAccessibilityEvent.run(View.java:19472)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5019)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
```

Thanks!!

**Comment by vinod1988** [comment]
I have added on Activity
I have the same problem

03-09 00:38:45.667 2486-2486/com.bitchy W/art: Before Android 4.1, method void com.etsy.android.grid.ExtendableListView.rememberSyncState() would have incorrectly overridden the package-private method in android.widget.AdapterView
03-09 00:38:45.667 2486-2486/com.bitchy W/art: Before Android 4.1, method void com.etsy.android.grid.ExtendableListView.fillGap(boolean) would have incorrectly overridden the package-private method in android.widget.AbsListView
03-09 00:38:45.667 2486-2486/com.bitchy W/art: Before Android 4.1, method int com.etsy.android.grid.ExtendableListView.getFooterViewsCount() would have incorrectly overridden the package-private method in android.widget.AbsListView
03-09 00:38:45.667 2486-2486/com.bitchy W/art: Before Android 4.1, method int com.etsy.android.grid.ExtendableListView.getHeaderViewsCount() would have incorrectly overridden the package-private method in android.widget.AbsListView
03-09 00:38:45.667 2486-2486/com.bitchy W/art: Before Android 4.1, method void com.etsy.android.grid.ExtendableListView.invokeOnItemScrollListener() would have incorrectly overridden the package-private method in android.widget.AbsListView
03-09 00:38:45.667 2486-2486/com.bitchy W/art: Before Android 4.1, method void com.etsy.android.grid.ExtendableListView.reportScrollStateChange(int) would have incorrectly overridden the package-private method in android.widget.AbsListView

-
