### ISSUE TITLE
Crash on click and scroll

### ISSUE THREAD

**Issue by KrisGroove** [etsy/AndroidStaggeredGrid#82]
Log cat after CLICK:

```
03-26 12:54:31.490    2051-2051/pl.specify.blogexample E/InputEventReceiver﹕ Exception dispatching input event.
03-26 12:54:31.490    2051-2051/pl.specify.blogexample E/MessageQueue-JNI﹕ Exception in MessageQueue callback: handleReceiveCallback
03-26 12:54:31.500    2051-2051/pl.specify.blogexample E/MessageQueue-JNI﹕ java.lang.NoClassDefFoundError: android.support.v4.view.MotionEventCompat
            at com.etsy.android.grid.ExtendableListView.onTouchDown(ExtendableListView.java:815)
            at com.etsy.android.grid.ExtendableListView.onTouchEvent(ExtendableListView.java:692)
            at android.view.View.dispatchTouchEvent(View.java)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
            at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java)
            at android.app.Activity.dispatchTouchEvent(Activity.java)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java)
            at android.view.View.dispatchPointerEvent(View.java)
            at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java)
            at android.os.MessageQueue.nativePollOnce(Native Method)
            at android.os.MessageQueue.next(MessageQueue.java)
            at android.os.Looper.loop(Looper.java)
            at android.app.ActivityThread.main(ActivityThread.java)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
            at dalvik.system.NativeStart.main(Native Method)
03-26 12:54:31.500    2051-2051/pl.specify.blogexample W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41166540)
03-26 12:54:31.510    2051-2051/pl.specify.blogexample E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: android.support.v4.view.MotionEventCompat
            at com.etsy.android.grid.ExtendableListView.onTouchDown(ExtendableListView.java:815)
            at com.etsy.android.grid.ExtendableListView.onTouchEvent(ExtendableListView.java:692)
            at android.view.View.dispatchTouchEvent(View.java)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
            at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java)
            at android.app.Activity.dispatchTouchEvent(Activity.java)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java)
            at android.view.View.dispatchPointerEvent(View.java)
            at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java)
            at android.os.MessageQueue.nativePollOnce(Native Method)
            at android.os.MessageQueue.next(MessageQueue.java)
            at android.os.Looper.loop(Looper.java)
            at android.app.ActivityThread.main(ActivityThread.java)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
            at dalvik.system.NativeStart.main(Native Method)
```

And when try scroll

```
03-26 12:55:50.640    2359-2359/pl.specify.blogexample D/SampleAdapter﹕ getPositionRatio:4 ratio:1.204275349461236
03-26 12:55:50.640    2359-2359/pl.specify.blogexample D/SampleAdapter﹕ getView position:4 h:1.204275349461236
03-26 12:55:50.640    2359-2359/pl.specify.blogexample D/StaggeredGridActivity﹕ onScroll firstVisibleItem:0 visibleItemCount:6 totalItemCount:32
03-26 12:55:50.660    2359-2359/pl.specify.blogexample D/memalloc﹕ ion: Mapped buffer base:0x59e7e000 size:1536000 offset:0 fd:89
03-26 12:55:50.660    2359-2359/pl.specify.blogexample D/memalloc﹕ ion: Mapped buffer base:0x56c1a000 size:4096 offset:0 fd:91
03-26 12:55:50.660    2359-2359/pl.specify.blogexample E/InputEventReceiver﹕ Exception dispatching input event.
03-26 12:55:50.660    2359-2359/pl.specify.blogexample W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x41166540)
03-26 12:55:50.680    2359-2359/pl.specify.blogexample E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: android.support.v4.view.MotionEventCompat
            at com.etsy.android.grid.ExtendableListView.onTouchMove(ExtendableListView.java:852)
            at com.etsy.android.grid.ExtendableListView.onTouchEvent(ExtendableListView.java:696)
            at android.view.View.dispatchTouchEvent(View.java)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
            at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java)
            at android.app.Activity.dispatchTouchEvent(Activity.java)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java)
            at android.view.View.dispatchPointerEvent(View.java)
            at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java)
            at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
            at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java)
            at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java)
            at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java)
            at android.view.Choreographer.doCallbacks(Choreographer.java)
            at android.view.Choreographer.doFrame(Choreographer.java)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java)
            at android.os.Handler.handleCallback(Handler.java)
            at android.os.Handler.dispatchMessage(Handler.java)
            at android.os.Looper.loop(Looper.java)
            at android.app.ActivityThread.main(ActivityThread.java)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
            at dalvik.system.NativeStart.main(Native Method)
```

Code is copy from sample!

**Comment by venki0552** [comment]
yes got the same exception!
