### ISSUE TITLE
Nullpointer on init of grid

### ISSUE THREAD

**Issue by edwinhermkens** [etsy/AndroidStaggeredGrid#84]
I've a normally working gridview implementation with endless scroll and pull to refresh. Strangly sometimes the app crashes on startup with the stacktrace below. I used both 1.03 an 1.04 but it didn't make any change. Anyone familiar with this?  

stacktrace:

```
java.lang.NullPointerException
        at com.etsy.android.grid.ExtendableListView.setupChild(ExtendableListView.java:1425)
        at com.etsy.android.grid.ExtendableListView.makeAndAddView(ExtendableListView.java:1404)
        at com.etsy.android.grid.ExtendableListView.fillSpecific(ExtendableListView.java:1351)
        at com.etsy.android.grid.ExtendableListView.layoutChildren(ExtendableListView.java:592)
        at com.etsy.android.grid.StaggeredGridView.layoutChildren(StaggeredGridView.java:354)
        at com.etsy.android.grid.ExtendableListView.onLayout(ExtendableListView.java:513)
```

.... and so on ....
         at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by jaboston** [comment]
has anyone tried solving this?
