### ISSUE TITLE
NullPointerException from onSaveInstanceState

### ISSUE THREAD

**Issue by xicabin** [etsy/AndroidStaggeredGrid#93]
The app crash sometimes ( not often ) with the exception below, will anybody tell me how to handle it, thanks in advance ?

<pre>
java.lang.NullPointerException
    at android.widget.AbsListView.onSaveInstanceState(AbsListView.java:1017)
    at com.etsy.android.grid.ExtendableListView.onSaveInstanceState(Unknown Source)
    at com.etsy.android.grid.StaggeredGridView.onSaveInstanceState(Unknown Source)
    at android.view.View.dispatchSaveInstanceState(View.java:6208)
    at android.view.ViewGroup.dispatchFreezeSelfOnly(ViewGroup.java:1203)
    at android.widget.AdapterView.dispatchSaveInstanceState(AdapterView.java:759)
    at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:1190)
    at android.view.ViewGroup.dispatchSaveInstanceState(ViewGroup.java:1190)
    at android.view.View.saveHierarchyState(View.java:6191)
    at android.support.v4.app.o.f(Unknown Source)
    at android.support.v4.app.o.g(Unknown Source)
    at android.support.v4.app.o.h(Unknown Source)
    at android.support.v4.app.FragmentActivity.onSaveInstanceState(Unknown Source)
    at android.app.Activity.performSaveInstanceState(Activity.java:1046)
    at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1181)
    at android.app.ActivityThread.performPauseActivity(ActivityThread.java:2336)
    at android.app.ActivityThread.performPauseActivity(ActivityThread.java:2311)
    at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:2291)
    at android.app.ActivityThread.access$1700(ActivityThread.java:117)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:130)
    at android.app.ActivityThread.main(ActivityThread.java:3683)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:906)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:664)
    at dalvik.system.NativeStart.main(Native Method)
</pre>

**Comment by 337240552** [comment]
I got this bug too, hope fix it
